spring.application.name=calculadora-inteligente
server.port=8082

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3:latest

app.ai.timeout-seconds=120
app.ai.tools-enabled=false
